require "../src/fused_json"

# Generates a large decoded prefix without retaining it or reading it from
# storage. The parser must still consume every generated byte.
private class LargeOffsetGeneratedIO < IO
  getter bytes_read : Int64
  getter read_calls : Int64

  @prefix_remaining : Int64
  @suffix : String
  @suffix_position : Int32

  def initialize(prefix_bytes : Int64, suffix : String)
    raise ArgumentError.new("prefix_bytes must not be negative") if prefix_bytes < 0

    @prefix_remaining = prefix_bytes
    @suffix = suffix
    @suffix_position = 0
    @bytes_read = 0_i64
    @read_calls = 0_i64
  end

  def read(slice : Bytes) : Int32
    return 0 if slice.empty?

    @read_calls += 1
    written = 0

    if @prefix_remaining > 0
      count = Math.min(@prefix_remaining, slice.size.to_i64).to_i32
      slice[0, count].fill(0x20_u8)
      @prefix_remaining -= count
      written += count
    end

    suffix_bytes = @suffix.to_slice
    suffix_remaining = suffix_bytes.size - @suffix_position
    if written < slice.size && suffix_remaining > 0
      count = Math.min(slice.size - written, suffix_remaining)
      slice[written, count].copy_from(suffix_bytes[@suffix_position, count])
      @suffix_position += count
      written += count
    end

    @bytes_read += written
    written
  end

  def write(slice : Bytes) : Nil
    raise IO::Error.new("LargeOffsetGeneratedIO is read-only")
  end
end

prefix_bytes = (1_i64 << 32) + 37
suffix = "null"
input = LargeOffsetGeneratedIO.new(prefix_bytes, suffix)
limits = FusedJSON::Limits.new(max_document_bytes: prefix_bytes)
started = Time.instant

begin
  FusedJSON::PullParser.new(
    input,
    buffer_size: FusedJSON::StreamingPullParser::MAX_BUFFER_SIZE,
    limits: limits
  )
rescue error : FusedJSON::ParseError
  unless error.byte_offset == prefix_bytes
    raise "expected byte offset #{prefix_bytes}, got #{error.byte_offset}"
  end
  unless error.location_i64 == {1_i64, prefix_bytes + 1}
    raise "expected location {1, #{prefix_bytes + 1}}, got #{error.location_i64}"
  end
  unless prefix_bytes < input.bytes_read <= prefix_bytes + suffix.bytesize
    raise "unexpected generated byte count #{input.bytes_read}"
  end

  elapsed = (Time.instant - started).total_seconds
  puts "post-2^32 offset check passed: offset=#{error.byte_offset} bytes_read=#{input.bytes_read} read_calls=#{input.read_calls} seconds=#{elapsed.round(3)}"
else
  raise "expected max_document_bytes to reject the sentinel at byte #{prefix_bytes}"
end
